name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          USERNAME: ${{ secrets.EC2_USER_NAME }}
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "Connecting to $USERNAME@$HOST"
          ssh -i ~/.ssh/id_rsa $USERNAME@$HOST 'cd /var/www/html/ForumProject && git fetch origin main && git reset --hard origin/main'
